### ISSUE TITLE
Boleh dipecah databasenya?

### ISSUE THREAD

**Issue by chez14** [edwinkun/database-kodepos-seluruh-indonesia#1]
Hai, dari repo edwardsamuel/Wilayah-Administratif-Indonesia#7, saya nemu repo ini punya kode pos.

Boleh dipecah ke beberapa database (Provinsi, Kota, dst)?

Thanks. 👍

**Comment by edwin** [comment]
hi mas @onlyongunz 
bisa tau maksudnya dipecah seperti apa, 1 table untuk 1 provinsi atau gimana?

**Comment by chez14** [comment]
iya, di grup berdasarkan kota, provinsi, dst... hehe

**Comment by edwin** [comment]
loh tinggal query aja, ada field provinsi, kabupaten/kota dan select pakai where bukan?
atau mas ada ide lain?

**Comment by imam** [comment]
@edwinkun maybe dipisah ke beberapa file biar lebih ringan maksudnya @onlyongunz . By the way mau nanya, gan edwin bagaimana caranya untuk dapatin data ini?

**Comment by edwin** [comment]
@onlyongunz 
beberapa file lalu jadi brp table om?
bukannya malah menyulitkan apabila dipecah ke beberapa table yg berbeda?

@imam 
aku scrapping dari nomor(dot)net, namun dilengkapi manual satu-satu dengan data pt pos

**Comment by imam** [comment]
@edwinkun manual? Ini awalnya untuk projekkah? Atau iseng-iseng? By the way lagi, akun github @edwin itu bisa di name squat loh gara-gara lama gak dipakai (Kayak saya name squat @imam ini dari @imamassi). Minta langsung ke githubnya kalau tertarik di https://github.com/contact :) .

**Comment by edwin** [comment]
kebetulan kemarin ada pekerjaan yg membutuhkan list kodepos
nyari online engga ada yg bisa provide, jadi terpaksa generate sendiri
sekalian aja gw bikin open di github :smile:

**Comment by imam** [comment]
Cool-cool :hamster: . Sayang banget gak ada yang dari official. Itu 11 fork dari temen kerjaan semua? Atau orang yang gak dikenal?

**Comment by edwin** [comment]
tetangga dunia maya mas, sepertinya memang rada banyak yg butuh data kode kewilayahan dan kodepos :eyes:

**Comment by chez14** [comment]
@edwinkun eheheh tujuan utamanya sih ke beberapa table.
Soalnya buat orang *lemah* kek saya, butuh ORM/ODM biar enak heheheh...

**Comment by edwin** [comment]
hahaa asyik, gw udh dapet username @edwin
eh, btw gw close ya issuenya. Thanks all

**Comment by chez14** [comment]
nuuu kenapaahhh :'

**Comment by edwin** [comment]
ya soalnya ga ada hubungannya antara pecah table dengan ORM :man_facepalming:

**Comment by chez14** [comment]
ahh oke deh 😢
