### ISSUE TITLE
perbedaan jumlah desa/kelurahan menurut BPS dan 

### ISSUE THREAD

**Issue by sugenk** [edwinkun/database-kodepos-seluruh-indonesia#2]
data jumlah desa/kelurahan dari data kantor pos ini tahun 2015 adalah 81,082

menurut Peraturan Kepala Badan Pusat Statistik Nomor 66 Tahun 2016 tentang Kode dan Wilayah Kerja Statistik Tahun 2016 adalah 82.030

menurut Peraturan Menteri Dalam Negeri Nomor 56 Tahun 2015 tentang Kode dan data wilayah Administrasi pemerintahan disebutkan bahwa jumlah Desa dan kelurahan di Indonesia adalah 83.184 (74.754 Desa + 8.430 Kelurahan)

Apakah ada update terbaru?

**Comment by sugenk** [comment]
Okey, sudah dapat di repo lain (tapi tanpa kodepos) ...

Kode dan Data Wilayah Administrasi Indonesia sesuai Permendagri No.137 Tahun 2017
https://github.com/cahyadsn/wilayah
https://github.com/cahyadsn/wilayah/blob/master/wilayah_2018.sql (updated)

**Comment by edwin** [comment]
@sugenk 
nyari data update-nya agak susah mas, 
tapi nanti aku coba cari, misalkan ada akan aku update. 
dan misalkan mas mau, mas juga bisa fork kemudian update data di repo ini
